name: lib-nelkinda CI/CD

on:
  push:
    branches: [ trunk ]
    paths-ignore:
      - 'assets/**'
      - 'doc/**'
      - 'host/**'
      - 'README.md'
      - '**/README.md'
  pull_request:
    branches: [ trunk ]
    paths-ignore:
      - 'assets/**'
      - 'doc/**'
      - 'host/**'
      - 'README.md'
      - '**/README.md'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-java@v4.6.0
      with:
        cache: gradle
        distribution: 'zulu'
        java-version: '21'

    - name: Build and Test
      env:
        BUILD_NUMBER: ${{ github.run_number }}
        GIT_SHA: ${{ github.sha }}
      run: make pipeline
